# Primer divague de todo lo aprendido

In [2]:
import numpy as np

In [3]:
a = np.array(['hola','que','tal','todo','bien','vos'])
a[[3,5]]
#Asi indexo arrays unidimensionales

array(['todo', 'vos'], dtype='<U4')

In [37]:
print(a[0],[2])

hola [2]


In [66]:
b = np.array([['hola','que','tal'],['todo','bien','vos']])
b

array([['hola', 'que', 'tal'],
       ['todo', 'bien', 'vos']], dtype='<U4')

In [67]:
print(b[1,[0,2]])

['todo' 'vos']


In [68]:
modificacion1 = b[1,[0,2]]
modificacion1.reshape(2,1)

array([['todo'],
       ['vos']], dtype='<U4')

In [69]:
modificacion1[0] = 'mod1'
modificacion1[1] = 'mod2'
print(modificacion1)


['mod1' 'mod2']


In [70]:
print(b)

[['hola' 'que' 'tal']
 ['todo' 'bien' 'vos']]


In [75]:
b[1,[0,2]] = modificacion1

In [95]:
b

array([['hola', 'que', 'tal'],
       ['mod1', 'bien', 'mod2']], dtype='<U4')

## Numeros random

In [97]:
random = np.random.randint(36, size=(6,6))
random

array([[ 7, 33, 13, 18, 34, 21],
       [19,  9, 20, 35,  8, 35],
       [13, 34, 18,  8, 18, 11],
       [22,  4, 28, 21, 25,  9],
       [35, 33, 24, 19, 26, 13],
       [ 2, 33, 18, 20, 24,  8]])

In [99]:
random[1,[5]] = 1000

In [102]:
random = random.astype('float64')

In [103]:
random

array([[   7.,   33.,   13.,   18.,   34.,   21.],
       [  19.,    9.,   20.,   35.,    8., 1000.],
       [  13.,   34.,   18.,    8.,   18.,   11.],
       [  22.,    4.,   28.,   21.,   25.,    9.],
       [  35.,   33.,   24.,   19.,   26.,   13.],
       [   2.,   33.,   18.,   20.,   24.,    8.]])

In [104]:
random = random.astype('int32')
print(random)

[[   7   33   13   18   34   21]
 [  19    9   20   35    8 1000]
 [  13   34   18    8   18   11]
 [  22    4   28   21   25    9]
 [  35   33   24   19   26   13]
 [   2   33   18   20   24    8]]


In [126]:
cortada = random[3:,:3]
print(cortada)


[[22  4 28]
 [35 33 24]
 [ 2 33 18]]


In [128]:
cortada = cortada+5

In [129]:
print(cortada)

[[27  9 33]
 [40 38 29]
 [ 7 38 23]]


In [131]:
random[3:,:3] = cortada
random

array([[   7,   33,   13,   18,   34,   21],
       [  19,    9,   20,   35,    8, 1000],
       [  13,   34,   18,    8,   18,   11],
       [  27,    9,   33,   21,   25,    9],
       [  40,   38,   29,   19,   26,   13],
       [   7,   38,   23,   20,   24,    8]], dtype=int32)

In [132]:
random > 20

array([[False,  True, False, False,  True,  True],
       [False, False, False,  True, False,  True],
       [False,  True, False, False, False, False],
       [ True, False,  True,  True,  True, False],
       [ True,  True,  True, False,  True, False],
       [False,  True,  True, False,  True, False]])

In [139]:
nuevoRandom = np.where(random>20,'es mayor',1)

In [141]:
random = nuevoRandom
random

array([['1', 'es mayor', '1', '1', 'es mayor', 'es mayor'],
       ['1', '1', '1', 'es mayor', '1', 'es mayor'],
       ['1', 'es mayor', '1', '1', '1', '1'],
       ['es mayor', '1', 'es mayor', 'es mayor', 'es mayor', '1'],
       ['es mayor', 'es mayor', 'es mayor', '1', 'es mayor', '1'],
       ['1', 'es mayor', 'es mayor', '1', 'es mayor', '1']], dtype='<U21')

# Mas random

In [7]:
a = np.random.randint(36, size=(6,6,6))
a

array([[[34, 29, 18, 30, 32, 29],
        [ 5, 30, 13, 16, 31,  5],
        [14,  9, 11, 28, 17,  4],
        [33, 26, 20, 30, 14, 21],
        [28, 20, 23, 14, 31, 32],
        [23, 22,  1, 33,  5, 25]],

       [[23, 25, 31,  6, 22, 21],
        [11, 22, 25,  0,  2, 27],
        [14,  0, 20, 15,  3, 23],
        [26, 11, 21,  8, 14, 29],
        [ 3, 18,  1, 27, 24, 17],
        [14,  9,  8, 31,  1,  3]],

       [[30, 29, 35, 31, 12, 10],
        [ 9, 26, 22, 27, 11, 31],
        [29, 34, 10,  7, 34, 25],
        [31,  4, 26, 33, 23, 13],
        [ 3, 21, 25, 16,  2,  4],
        [30,  1, 25, 13,  6, 34]],

       [[ 1, 22,  9,  4,  3, 25],
        [30, 10, 32, 27,  1, 23],
        [32, 20, 14,  6, 12, 23],
        [ 3, 31, 14,  9, 14, 30],
        [15, 18, 16, 10, 29, 13],
        [15, 19,  6, 21, 11, 23]],

       [[27, 32,  4,  2, 15, 32],
        [27, 30,  1, 34, 30, 29],
        [ 8, 29, 20, 30, 26, 27],
        [ 9,  7, 17, 11, 35,  2],
        [18, 11, 32, 32, 10,  9],
      

In [8]:
b = a[4,:,:3]
b

array([[27, 32,  4],
       [27, 30,  1],
       [ 8, 29, 20],
       [ 9,  7, 17],
       [18, 11, 32],
       [ 1, 32, 21]])

In [10]:
c = b[:,0]
c

array([27, 27,  8,  9, 18,  1])

In [11]:
c[0] = c[0]-1
c

array([26, 27,  8,  9, 18,  1])

In [12]:
b[:,0] = c
b

array([[26, 32,  4],
       [27, 30,  1],
       [ 8, 29, 20],
       [ 9,  7, 17],
       [18, 11, 32],
       [ 1, 32, 21]])

In [14]:
a[4,:,:3] = b
a.ndim

3