# Primera practica de todo lo aprendido

In [2]:
import numpy as np

In [3]:
a = np.array(['hola','que','tal','todo','bien','vos'])
a[[3,5]]
#Asi indexo arrays unidimensionales

array(['todo', 'vos'], dtype='<U4')

In [4]:
print(a[0],[2])

hola [2]


In [5]:
b = np.array([['hola','que','tal'],['todo','bien','vos']])
b

array([['hola', 'que', 'tal'],
       ['todo', 'bien', 'vos']], dtype='<U4')

In [6]:
print(b[1,[0,2]])

['todo' 'vos']


In [7]:
modificacion1 = b[1,[0,2]]
modificacion1.reshape(2,1)

array([['todo'],
       ['vos']], dtype='<U4')

In [8]:
modificacion1[0] = 'mod1'
modificacion1[1] = 'mod2'
print(modificacion1)


['mod1' 'mod2']


In [9]:
print(b)

[['hola' 'que' 'tal']
 ['todo' 'bien' 'vos']]


In [10]:
b[1,[0,2]] = modificacion1

In [11]:
b

array([['hola', 'que', 'tal'],
       ['mod1', 'bien', 'mod2']], dtype='<U4')

## Numeros random

In [12]:
random = np.random.randint(36, size=(6,6))
random

array([[26, 18,  5, 20, 27, 13],
       [ 2,  9, 20,  4, 23, 27],
       [29, 10, 14, 31, 18,  2],
       [23, 13,  2, 17,  1, 13],
       [14, 31,  8, 20,  0, 19],
       [35, 11, 10, 29, 16, 21]])

In [13]:
random[1,[5]] = 1000

In [14]:
random = random.astype('float64')

In [15]:
random

array([[  26.,   18.,    5.,   20.,   27.,   13.],
       [   2.,    9.,   20.,    4.,   23., 1000.],
       [  29.,   10.,   14.,   31.,   18.,    2.],
       [  23.,   13.,    2.,   17.,    1.,   13.],
       [  14.,   31.,    8.,   20.,    0.,   19.],
       [  35.,   11.,   10.,   29.,   16.,   21.]])

In [16]:
random = random.astype('int32')
print(random)

[[  26   18    5   20   27   13]
 [   2    9   20    4   23 1000]
 [  29   10   14   31   18    2]
 [  23   13    2   17    1   13]
 [  14   31    8   20    0   19]
 [  35   11   10   29   16   21]]


In [17]:
cortada = random[3:,:3]
print(cortada)


[[23 13  2]
 [14 31  8]
 [35 11 10]]


In [18]:
cortada = cortada+5

In [19]:
print(cortada)

[[28 18  7]
 [19 36 13]
 [40 16 15]]


In [20]:
random[3:,:3] = cortada
random

array([[  26,   18,    5,   20,   27,   13],
       [   2,    9,   20,    4,   23, 1000],
       [  29,   10,   14,   31,   18,    2],
       [  28,   18,    7,   17,    1,   13],
       [  19,   36,   13,   20,    0,   19],
       [  40,   16,   15,   29,   16,   21]], dtype=int32)

In [21]:
random > 20

array([[ True, False, False, False,  True, False],
       [False, False, False, False,  True,  True],
       [ True, False, False,  True, False, False],
       [ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [ True, False, False,  True, False,  True]])

In [22]:
nuevoRandom = np.where(random>20,'es mayor',1)

In [23]:
random = nuevoRandom
random

array([['es mayor', '1', '1', '1', 'es mayor', '1'],
       ['1', '1', '1', '1', 'es mayor', 'es mayor'],
       ['es mayor', '1', '1', 'es mayor', '1', '1'],
       ['es mayor', '1', '1', '1', '1', '1'],
       ['1', 'es mayor', '1', '1', '1', '1'],
       ['es mayor', '1', '1', 'es mayor', '1', 'es mayor']], dtype='<U21')

# Mas random

In [24]:
a = np.random.randint(36, size=(6,6,6))
a

array([[[11, 13,  0, 28, 28, 34],
        [19, 34,  2, 30, 14,  1],
        [13, 32, 21, 18, 16, 28],
        [28, 18,  4, 23, 23, 14],
        [20, 33, 22, 17, 14,  1],
        [10, 32,  4,  5,  3, 34]],

       [[21, 20,  1, 25, 17, 25],
        [10, 28,  7, 13,  5, 14],
        [15, 30, 25, 25, 24,  9],
        [27, 27, 28, 27, 23,  3],
        [ 8,  6, 26,  3, 26, 23],
        [21, 26, 13, 35, 32, 19]],

       [[13,  4, 32, 11, 20, 18],
        [21,  7, 15, 14, 16, 27],
        [18, 31, 32, 13, 32, 22],
        [ 9,  8, 34, 15,  0, 23],
        [ 4,  6, 17, 12, 29, 22],
        [19, 20,  8, 16, 13,  7]],

       [[16, 22, 20, 13, 21,  1],
        [ 4, 32,  1, 13,  8, 12],
        [ 8, 34, 20, 22, 26, 14],
        [ 2, 11,  7, 27, 34, 17],
        [13, 21,  6,  3, 11, 24],
        [ 7, 13, 30,  9, 18,  9]],

       [[13,  0, 32,  8, 31, 20],
        [33,  8,  8, 29,  1, 18],
        [ 6, 22, 29, 27, 20, 11],
        [ 9, 10,  3,  3,  6, 17],
        [14,  9,  6, 12,  1, 29],
      

In [25]:
b = a[4,:,:3]
b

array([[13,  0, 32],
       [33,  8,  8],
       [ 6, 22, 29],
       [ 9, 10,  3],
       [14,  9,  6],
       [ 2, 12, 31]])

In [26]:
c = b[:,0]
c

array([13, 33,  6,  9, 14,  2])

In [27]:
c[0] = c[0]-1
c

array([12, 33,  6,  9, 14,  2])

In [28]:
b[:,0] = c
b

array([[12,  0, 32],
       [33,  8,  8],
       [ 6, 22, 29],
       [ 9, 10,  3],
       [14,  9,  6],
       [ 2, 12, 31]])

In [29]:
a[4,:,:3] = b
a.ndim

3

In [37]:
print(a)

[[[11 13  0 28 28 34]
  [19 34  2 30 14  1]
  [13 32 99 99 99 99]
  [28 18  4 23 23 14]
  [20 33 22 17 14  1]
  [10 32  4  5  3 34]]

 [[21 20  1 25 17 25]
  [10 28  7 13  5 14]
  [15 30 25 25 24  9]
  [27 27 28 27 23  3]
  [ 8  6 26  3 26 23]
  [21 26 13 35 32 19]]

 [[13  4 32 11 20 18]
  [21  7 15 14 16 27]
  [18 31 32 13 32 22]
  [ 9  8 34 15  0 23]
  [ 4  6 17 12 29 22]
  [19 20  8 16 13  7]]

 [[16 22 20 13 21  1]
  [ 4 32  1 13  8 12]
  [ 8 34 20 22 26 14]
  [ 2 11  7 27 34 17]
  [13 21  6  3 11 24]
  [ 7 13 30  9 18  9]]

 [[12  0 32  8 31 20]
  [33  8  8 29  1 18]
  [ 6 22 29 27 20 11]
  [ 9 10  3  3  6 17]
  [14  9  6 12  1 29]
  [ 2 12 31  3  7  3]]

 [[18  1  5 32 34  4]
  [27 21 15 26 34 12]
  [14 26 28  2 15 11]
  [33 25 23 20 32 12]
  [27 21 19 31 16  8]
  [21 21 31 16 30  5]]]


In [33]:
d= a[0,2,:]
d

array([13, 32, 21, 18, 16, 28])

In [35]:
d[2:] = 99

In [36]:
d

array([13, 32, 99, 99, 99, 99])